### ISSUE TITLE
All extension don't work, no load of mangas

### ISSUE THREAD

**Issue by campana-giuseppe** [Suwayomi/docker-tachidesk#10]
Hi,
I have installed the latest version available,and I have 2 problems:

1) the extensions are quietly loaded-downloaded-installed, but once opened to search for a manga they load endlessly. I've tried clearing the cache and cookies of the browser, tried incognito, set the dns of the machine with 1.1.1.1, tried from a tachidesk client that connects and reads the data correctly but even there does not load the manga from the extensions, tried multiple extensions and the same extensions work on tachiyomi

2) restarting the container or if by chance it stops and restarts all settings data are lost, e.g. installed extensions

Below is my compose:

```
---
version: "2.1"
services:
  tachidesk:
    image: ghcr.io/suwayomi/tachidesk
    container_name: tachidesk
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/Rome # Use TZ database name from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    volumes:
      - /home/server/docker-applications/tachidesk/config/:/home/suwayomi/.local/share/Tachidesk
      - /home/hhd/seagate2tb/nextcloud/badbeppe/files/file-storage/tachidesk-downloads/:/home/suwayomi/.local/share/Tachidesk/downloads
    ports:
      - 8087:4567
    restart: unless-stopped

```
My logs:

```

                                                                ************README***********
-> It is essential that u read readme for ghcr.io/suwayomi/tachidesk before running this container
-> Readme for ghcr.io/suwayomi/tachidesk is available at https://github.com/suwayomi/docker-tachidesk 
                                                                *****************************
Tachidesk data location inside the container -> /home/suwayomi/.local/share/Tachidesk
The server is running by default configuration on  http://localhost:4567
log file location inside the container -> /home/suwayomi/.local/share/Tachidesk/logfile.log
```

**Comment by campana-giuseppe** [comment]
Data loss seems to be resolved after recreating the container.
Regarding loading manga using various extensions (which work on tachiyomi) I still can't solve it, it seems to be unable to connect. It shows a long load that ends with a blank screen, no information about the manga is loaded (the page structure doesn't load either).

Any tips to try are welcome =)

**Comment by arbuilder** [comment]
If it worked on earlier version then it is an issue with the newer tachidesk jar and for fixing this issue you need to create an issue on tachidesk repo

**Comment by campana-giuseppe** [comment]
> If it worked on earlier version then it is an issue with the newer tachidesk jar and for fixing this issue you need to create an issue on tachidesk repo

I don't know about earlier versions, I can try using an earlier version and confirm if it is a problem with this latest version.

**Comment by campana-giuseppe** [comment]
tested versions: 0.6.1 / 0.6.2 / 0.6.3 / preview
current status: the extensions load the list of manga with their covers without problems. Some extensions, after selecting the manga, load the list of chapters but do not load the images (after loading, everything remains black) and the other extensions do not load the list of chapters at all.

**Comment by arbuilder** [comment]
Then issue might be with extensions and unrelated to docker u need to create issue with tachidesk repo then we would know what is causing the issue.

**Comment by arbuilder** [comment]
> tested versions: 0.6.1 / 0.6.2 / 0.6.3 / preview current status: the extensions load the list of manga with their covers without problems. Some extensions, after selecting the manga, load the list of chapters but do not load the images (after loading, everything remains black) and the other extensions do not load the list of chapters at all.

does this work `ghcr.io/suwayomi/tachidesk:v0.5.4` , might be related to this https://github.com/Suwayomi/Tachidesk-Server/issues/346

**Comment by arbuilder** [comment]
can u try this code in compose and run as this is working for me on v0.6.3

```
version: '3.7'

services:

  tachidesk-docker:
    image: ghcr.io/suwayomi/tachidesk
    container_name: tachidesk-docker
    networks:
      custom_network1:
        ipv4_address: 172.22.2.11
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Calcutta
    volumes:
      - /<path to folder>/docker-config/tachidesk:/home/suwayomi/.local/share/Tachidesk # edit <path to folder>
    ports:
      - "4567:4567"
    restart: on-failure:3
	
   custom_network1:
     driver: bridge
     ipam:
       driver: default
       config:
         - subnet: 172.22.2.0/24
           gateway: 172.22.2.1  
```
