### ISSUE TITLE
Empty library after running 'docker compose down'

### ISSUE THREAD

**Issue by Hash6232** [Suwayomi/docker-tachidesk#124]
As per title, the server loses its library when I run `docker compose down` and then `docker compose up -d`. Why? I'm using the `stable` version.

```sh
cd /srv/docker/suwayomi
docker compose up -d
# restore backup..
docker compose down
docker compose up -d
# missing library..
```

```yaml
services:
  suwayomi:
    image: ghcr.io/suwayomi/suwayomi-server:stable
    container_name: suwayomi
    env_file: .env
    volumes:
      - ./backups:/home/suwayomi/.local/share/Tachidesk/backups
      - ./downloads:/home/suwayomi/.local/share/Tachidesk/downloads
      - /home/myuser/files/downloads/manga:/home/suwayomi/.local/share/Tachidesk/local
    ports:
      - "4567:4567"
    restart: on-failure:3
  flaresolverr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: suwayomi_flaresolverr
    env_file: .env
    ports:
      - "8191:8191"
    restart: unless-stopped

networks:
  default:
    name: caddy_net
    external: true
```
