### ISSUE TITLE
Running with custom UID/GID

### ISSUE THREAD

**Issue by Hash6232** [Suwayomi/docker-tachidesk#126]
Is there a proper way to start the container with a specific UID and GID? I run my containers with a specific system user that isn't `1000:1000` so I'm currently looking for the proper way to do it with this image. I've noticed that `1000:1000` is hardcoded in the `Dockerfile` when the image is generated. Right now I'm trying using `user: X:Y` and it appears to work since the generated file have the correct user and group on the host filesystem but when I run an interactive shell inside the container there's of course a mismatch:

```bash
groups: cannot find name for group ID 996
I have no name!@ea9a340f6632:/home/suwayomi$
```

```yaml
services:
  suwayomi:
    image: ghcr.io/suwayomi/suwayomi-server:stable
    container_name: suwayomi
    env_file: .env
    user: "$PUID:$PGID"
    ..
```
