### ISSUE TITLE
error line 21 permission denied

### ISSUE THREAD

**Issue by myfairx** [Suwayomi/docker-tachidesk#20]
hi. 

I used to have my tachidesk on  docker using custom environment pointing to my mounted drive and it works. however I had problem with os and reinstall. now the same compose wont work citing error permission

/home/suwayomi/startup/startup_script.sh: line 21: can't create /home/suwayomi/.local/share/Tachidesk/logfile.log: Permission denied
touch: /home/suwayomi/.local/share/Tachidesk/docker_touchfile: Permission denied

my compose file look like this:

```
---
version: '3.7'

services:

  tachidesk-docker:
    image: ghcr.io/suwayomi/tachidesk:preview
    container_name: tachi

    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Singapore

    volumes:
      - /srv/mergerfs/all/misc/media_temp/tachidesk:/home/suwayomi/.local/share/Tachidesk

    ports:
      - "4567:4567"
    restart: unless-stopped
```

I tried with latest and preview. IIRC I used to try with older releases prior updating

I'm on debian 11 x64 (omv6)
TQIA

**Comment by slhx99** [comment]
I have the same issue!

**Comment by myfairx** [comment]
> I have the same issue!

does yours work if no custom environment aka default?

mine works with default though I need easy access to download etc for archiving and encryption purposes

**Comment by slhx99** [comment]
I got mine working now! it seems that i messed up my host volume by adding a ```/``` at the end of the host volume.
doing ```sudo chmod 1000 <host volume file dir>``` works for me since then!

**Comment by myfairx** [comment]
glad it works for you

would you be so kind and share your compose? I might learn something or two

**Comment by slhx99** [comment]
Here's my docker-compose
I created a folder ```/portainer/Files/AppData/Config/tachidesk``` on my host and did ```sudo chmod 1000 /portainer/Files/AppData/Config/tachidesk``` before running the docker-compose

```
---
version: '3.7'

services:

  tachidesk-docker:
    image: ghcr.io/suwayomi/tachidesk:latest
    container_name: tachi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore # Use TZ database name from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - LOGGING=file
    volumes:
      - /portainer/Files/AppData/Config/tachidesk:/home/suwayomi/.local/share/Tachidesk # edit <path to folder> to your mapped folder
    ports:
      - '4567:4567'
    restart: on-failure:3
```
