### ISSUE TITLE
authentication options and uid problem

### ISSUE THREAD

**Issue by qowmq** [Suwayomi/docker-tachidesk#21]
1. No Authentication option in Tachidesk docker?

https://github.com/Suwayomi/Tachidesk-Server/wiki/Configuring-Tachidesk-Server#webui
next option:
```
server.basicAuthEnabled = false
server.basicAuthUsername = ""
server.basicAuthPassword = "" 
```

2. uid and gid problem
I want to run synology (DSM 7.1-42661 Update 4) from docker.
trying to map the folder _/home/suwayomi/.local/share/Tachidesk_ ghcr.io/suwayomi/tachidesk_ uid and gid are fixed at 1000.
Synology doesn't have an account with uid and gid of 1000.

I want to set the uid and gid directly.

Here is the compose file I tried:
```
version: '3.3'
services:
    suwayomi:
        image: ghcr.io/suwayomi/tachidesk:preview-java11
        container_name: tachidesk
        ports:
           - '4567:4567'
        volumes:
            - '/volume1/docker/tachidesk/config:/home/suwayomi/.local/share/Tachidesk'
        environment:
           - TZ=Asia/Seoul
           - PUID=1000
           - PGID=100
           - LOGGING=out
        #network_mode: "container:gluetun"
        restart: on-failure:3
```
