### ISSUE TITLE
Permission Issues

### ISSUE THREAD

**Issue by arbuilder** [Suwayomi/docker-tachidesk#22]
For permission issues test with develop tag i.e. - ghcr.io/suwayomi/tachidesk:develop
 and edit uid and gid in compose or command line as mentioned in this link  https://github.com/boxboat/fixuid

Ex - 

docker compose
```
tachidesk:
  image: ghcr.io/suwayomi/tachidesk:develop
  user: ${FIXUID:-1005}:${FIXGID:-1005}
  volumes:
    - etc: etc
```
command line 
`docker run --rm -it -u 1005:1005 <image name> sh`

mention it below if it works or doesnt work. i will not put it into stable untill majority of people test it out
