### ISSUE TITLE
Can't run latest image, but v0.6.5 can be started

### ISSUE THREAD

**Issue by mervynlam** [Suwayomi/docker-tachidesk#29]
latest can't run as commands
```bash
[root@mervyn tachidesk]# docker run -d -p 4567:4567 -v /mervyn/docker/tachidesk/datas/:/home/suwayomi/.local/share/Tachidesk ghcr.io/suwayomi/tachidesk:latest
9639bf79a4a6d5cd2da8f84ddd4053400030e25865c5f0fa360de5e057c00a0a
[root@mervyn tachidesk]# docker ps -a
CONTAINER ID        IMAGE                                            COMMAND                  CREATED             STATUS                     PORTS                                      NAMES
9639bf79a4a6        ghcr.io/suwayomi/tachidesk:latest                "/bin/sh /home/suway…"   5 seconds ago       Exited (1) 5 seconds ago                                              happy_hertz
[root@mervyn tachidesk]# docker logs happy_hertz


                                                                ************README***********
-> It is essential that u read readme for ghcr.io/suwayomi/tachidesk before running this container
-> Readme for ghcr.io/suwayomi/tachidesk is available at https://github.com/suwayomi/docker-tachidesk 
                                                                *****************************


Tachidesk data location inside the container -> /home/suwayomi/.local/share/Tachidesk

The server is running by default configuration on  http://localhost:4567
log file location inside the container -> /home/suwayomi/.local/share/Tachidesk/logfile.log
```

neither docker-compose.yml
```yml
[root@mervyn tachidesk]# cat docker-compose.yml
---
version: '3.7'

services:

  tachidesk-docker:
    image: ghcr.io/suwayomi/tachidesk
    container_name: tachidesk
    environment:
      - PUID=1000 # ( dont change, require uid to be 1000 )
      - PGID=1000 # ( dont change, require gid to be 1000 )
      - CST # Use TZ database name from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - LOGGING=file
    volumes:
      - ./datas/:/home/suwayomi/.local/share/Tachidesk # edit <path to folder> to your mapped folder
    ports:
      - "4567:4567"
    restart: on-failure:3
```
```bash
[root@mervyn tachidesk]# docker-compose up
[+] Running 1/0
 ⠿ Container tachidesk  Created                                                                                                                                                                                                                                          0.0s
Attaching to tachidesk
tachidesk  | 
tachidesk  | 
tachidesk  |                                                                 ************README***********
tachidesk  | -> It is essential that u read readme for ghcr.io/suwayomi/tachidesk before running this container
tachidesk  | -> Readme for ghcr.io/suwayomi/tachidesk is available at https://github.com/suwayomi/docker-tachidesk 
tachidesk  |                                                                 *****************************
tachidesk  | 
tachidesk  | 
tachidesk  | Tachidesk data location inside the container -> /home/suwayomi/.local/share/Tachidesk
tachidesk  | 
tachidesk  | The server is running by default configuration on  http://localhost:4567
tachidesk  | log file location inside the container -> /home/suwayomi/.local/share/Tachidesk/logfile.log
tachidesk exited with code 1
tachidesk exited with code 1
tachidesk exited with code 1
tachidesk exited with code 1
```

but it can run with 0.6.5 version
```bash
[root@mervyn tachidesk]# docker images
REPOSITORY                                TAG                 IMAGE ID            CREATED             SIZE
ghcr.io/suwayomi/tachidesk                0.6.5               66d42f8a1347        7 months ago        193MB
[root@mervyn tachidesk]# docker image inspect 66d42f8a1347 | grep version
                "org.opencontainers.image.version": "0.6.5",
[root@mervyn tachidesk]# docker run -d -p 4567:4567 -v /mervyn/docker/tachidesk/datas/:/home/suwayomi/.local/share/Tachidesk ghcr.io/suwayomi/tachidesk:0.6.5
ec886d239dbb91126dc4e53f8ecd7692e4ccc0964bace5ca468410dc6e0d3342
[root@mervyn tachidesk]# docker ps -a
CONTAINER ID        IMAGE                                            COMMAND                  CREATED             STATUS              PORTS                                      NAMES
ec886d239dbb        ghcr.io/suwayomi/tachidesk:0.6.5                 "/bin/sh /home/suway…"   4 seconds ago       Up 3 seconds        0.0.0.0:4567->4567/tcp                     fervent_ganguly
```

Is there any problem with my process?
