### ISSUE TITLE
Custom DNS configuration sometimes required to get around certain Extensions bans

### ISSUE THREAD

**Issue by ghost** [Suwayomi/docker-tachidesk#47]
My ISP has soft banned MangaDex so I always need to use a DNS different from the one offered by my ISP to get around the block. On my phone it's easily done by using the "one.one.one.one" address in the Networking configs but I noticed the default compose file or the documentation itself didn't address the problem.

In docker, using a `--dns "1.1.1.1"` is all you have to do to make your container use a different DNS address. Maybe an environment variable or commented out line can be added somewhere? Here's my current compose file:

```yml
version: '3.7'
services:
  suwayomi:
    image: ghcr.io/suwayomi/tachidesk:stable
    environment:
      - TZ=Europe/Dublin # Use TZ database name from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - DEBUG=true
      - BIND_IP=0.0.0.0
      - BIND_PORT=4567
      - SOCKS_PROXY_ENABLED=false
      - DOWNLOAD_AS_CBZ=true
      - MAX_PARALLEL_UPDATE=3
      - BASIC_AUTH_ENABLED=true
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=ahJTmbg2xsj2BAc
    dns:
      - "1.1.1.1"
    volumes:
      - /opt/tachiyomi:/home/suwayomi/.local/share/Tachidesk
    ports:
      - "4567:4567"
    restart: on-failure:3
```
